In [11]:
import numpy as np

In [12]:
valoraciones = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
valoraciones

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [13]:
valoraciones[0][1]

2

In [14]:
valoraciones[0,1]

2

In [15]:
valoraciones2 = np.array([[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[1,2,3,4],[5,6,7,8],[9,0,1,2]]])
valoraciones2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]]])

In [16]:
valoraciones2[0,1,1]

6

In [17]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
valoraciones2 + np.ones((3,3,4))


array([[[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10.,  1.,  2.,  3.]],

       [[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10.,  1.,  2.,  3.]],

       [[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10.,  1.,  2.,  3.]]])

In [20]:
np.mean(valoraciones2)

4.0

In [23]:
np.mean(valoraciones2, axis=0)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 0., 1., 2.]])

In [21]:
np.mean(valoraciones2, axis=1)

array([[5.        , 2.66666667, 3.66666667, 4.66666667],
       [5.        , 2.66666667, 3.66666667, 4.66666667],
       [5.        , 2.66666667, 3.66666667, 4.66666667]])

In [24]:
np.mean(valoraciones2, axis=2)

array([[2.5, 6.5, 3. ],
       [2.5, 6.5, 3. ],
       [2.5, 6.5, 3. ]])